// <autogenerated>
//   This file was generated by T4 code generator GenerateCMSEnums.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace Benefits.Shared.Enums
{    
    public enum CMSSite
    {
		Default = 0,
		Any = 117,
		Benefits = 116,
		Main = 115,
    }
}
