// <autogenerated>
//   This file was generated by T4 code generator GenerateCMSEnums.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace Benefits.Shared.Enums
{    
    public enum CMSTemplateType
    {
		Default = 0,
		AccountDashboardTemplate = 101,
		AccountFlyerTemplate = 118,
		BenefitsMarketingTemplate = 119,
		BookletTemplate = 103,
		ConferenceBroadcastTemplate = 114,
		ContactFormTemplate = 110,
		DocumentListingTemplate = 108,
		DocumentTableTemplate = 107,
		EmployeeHandbookTemplate = 113,
		ExternalSiteInfoTemplate = 111,
		InfoPageTemplate = 104,
		LoginPageContent = 109,
		MarketingLanderTemplate = 99,
		MarketingSubpageTemplate = 100,
		QuestionProSurveyTemplate = 112,
		RedirectTemplate = 106,
		SectionDashboardTemplate = 102,
    }
}
