// <autogenerated>
//   This file was generated by T4 code generator GenerateCMSEnums.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace Benefits.Shared.Enums
{    
    public enum LookupType
    {
		Default = 0,
		CMSSite = 10,
		CMSTemplateType = 9,
    }
}
